### PR TITLE
Fix robotpy-cscore install

### LINKED ISSUE #171: Basic Vision Example missing a dependency
The [Basic Vision Example](https://docs.wpilib.org/en/latest/docs/software/vision-processing/frcvision/basic-vision-example.html) ([src](https://github.com/wpilibsuite/frc-docs/blob/master/source/docs/software/vision-processing/frcvision/basic-vision-example.rst)) code does not seem to work with the `WPILibPi_image-v2021.1.1-beta-4` release.

I know this work is still flagged as in progress/unstable, but wanted to raise the issue in case it's something that was overlooked.

Not sure if this is an issue with the documentation or the image (or me :-D, if I'm overlooking a step)

```
Waiting 5 seconds...

Traceback (most recent call last):
  File "uploaded.py", line 1, in <module>

    from cscore import CameraServer
  File "/usr/local/lib/python3.7/dist-packages/cscore/__init__.py", line 1, in <module>
    from _cscore import *
```

### PR DESCRIPTION
**Pull request by PeterJohnson**
Also upgrade to robotpy-cscore 2020.0.1.

Partially fixes #171 (ntcore is still missing).

### CODE REVIEW

File: stage3/01-sys-tweaks/01-run.sh [hunk 1]
```diff
@@ -99,7 +99,7 @@ echo "__version__ = '2020.0.1'" > pynetworktables/_pynetworktables/_impl/version
 # robotpy-cscore
 tar xzf "${DOWNLOAD_DIR}/robotpy-cscore.tar.gz"
 mv robotpy-cscore-* robotpy-cscore
-echo "__version__ = '2020.0.0'" > robotpy-cscore/cscore/version.py
+echo "__version__ = '2020.0.1'" > robotpy-cscore/cscore/version.py
 pushd robotpy-cscore
 patch -p0 < "${SUB_STAGE_DIR}/files/robotpy-cscore.patch"
```
Comment (auscompgeek) [inline stage3/01-sys-tweaks/01-run.sh:104]: Double-checking this patch, it looks like this is in upstream now too.
